CREATE OR REPLACE PACKAGE COBRANZA AS 

	PROCEDURE GET_AGENDA(ID_AGENTE IN EMPRESAS.ID_EMPRESA%TYPE, RESPONSE OUT SYS_REFCURSOR);
	PROCEDURE GET_AGENTES(ID_EMPRESA IN AGENTES.ID_AGENTE%TYPE, RESPONSE OUT SYS_REFCURSOR);
	PROCEDURE CREAR_AGENDA;
END COBRANZA;
	
	
CREATE OR REPLACE PACKAGE BODY COBRANZA
AS

	PROCEDURE GET_AGENDA(ID_AGENTE IN EMPRESAS.ID_EMPRESA%TYPE, RESPONSE OUT SYS_REFCURSOR)
		IS 
		ayer DATE:= TO_CHAR((SYSDATE - 1),'DD-MON-YYYY');
		
		BEGIN 
			OPEN RESPONSE FOR 'SELECT ID_USER, FECHA FROM ASIGNACION WHERE ID_AGENTE = ID_AGENTE AND FECHA > ayer ORDER BY FECHA';
		END GET_AGENDA;

	PROCEDURE GET_AGENTES(ID_EMPRESA IN AGENTES.ID_AGENTE%TYPE, RESPONSE OUT SYS_REFCURSOR)
	AS
	BEGIN
		OPEN RESPONSE FOR 'SELECT ID_AGENTE,NOMBRE,CIUDAD FROM AGENTES WHERE ID_EMPRESA = ID_EMPRESA';
	END GET_AGENTES;

	PROCEDURE CREAR_AGENDA
	IS
	CURSOR USUARIOS IS SELECT ID_USER,TIPO_CLIENTE,MONTO_DEUDA,TIEMPO,CIUDAD FROM USUARIO_DEUDA WHERE ID_USER NOT IN (SELECT ID_USER FROM ASIGNACION);
	usuario USUARIOS%ROWTYPE;
	EMPRESA PARAMETROS.ID_EMPRESA%TYPE;
	PRODUCTOS NUMBER;
	RESPONSE SYS_REFCURSOR;
	RES AGENTES%ROWTYPE;
	CITAS NUMBER;
	BEGIN
		OPEN USUARIOS;
		FETCH USUARIOS INTO usuario;
		LOOP
			SELECT COUNT(*) INTO PRODUCTOS FROM CLIENTES WHERE ID_USER = usuario.ID_USER;
			SELECT ID_EMPRESA INTO EMPRESA  FROM PARAMETROS WHERE TIPO_CLIENTE = usuario.TIPO_CLIENTE
			AND usuario.MONTO_DEUDA BETWEEN DEUDA_MIN AND DEUDA_MAX 
			AND MONTHS_BETWEEN(usuario.TIEMPO, SYSDATE) BETWEEN ANTIGUEDAD_MIN AND ANTIGUEDAD_MAX
			AND usuario.CIUDAD = CIUDAD
			AND PRODUCTOS BETWEEN PRODUCTOS_MIN AND PRODUCTOS_MAX;
		
			COBRANZA.GET_AGENTES(EMPRESA,RESPONSE);
			FETCH RESPONSE INTO RES;
			LOOP
				SELECT COUNT(*) INTO CITAS  FROM ASIGNACION WHERE ID_AGENTE = RES.ID_AGENTE AND ASIGNACION.FECHA = SYSDATE;
				IF EMPRESA = 1 AND CITAS < 8 AND RES.CIUDAD = usuario.CIUDAD THEN
					INSERT INTO ASIGNACION VALUES(DEFAULT, usuario.ID_USER,RES.ID_AGENTE,SYSDATE);
					EXIT;
				ELSIF EMPRESA = 2 AND CITAS < 6 AND RES.CIUDAD = usuario.CIUDAD THEN
					INSERT INTO ASIGNACION VALUES(DEFAULT, usuario.ID_USER,RES.ID_AGENTE,SYSDATE);
					EXIT;
				END IF;
				FETCH RESPONSE INTO RES;
				EXIT WHEN RESPONSE%NOTFOUND;
			END LOOP;
			COMMIT;
			CLOSE RESPONSE;
			FETCH USUARIOS INTO usuario;
			EXIT WHEN USUARIOS%NOTFOUND;
		END LOOP;
		COMMIT;
		CLOSE USUARIOS;
	END CREAR_AGENDA;
END COBRANZA;

