CREATE SEQUENCE SEQ_USUARIO START WITH 1;

CREATE TABLE USUARIO_DEUDA (ID_USER NUMBER DEFAULT SEQ_USUARIO.nextval PRIMARY KEY  NOT NULL,
NOMBRE VARCHAR2(20) NOT NULL, 
TIPO_CLIENTE VARCHAR2(20) NOT NULL, 
DIRECCION VARCHAR(50) NOT NULL,
CELULAR NUMBER NOT NULL,
CEDULA NUMBER NOT NULL,
MONTO_DEUDA NUMBER NOT NULL,
TIEMPO DATE NOT NULL,
CIUDAD VARCHAR2(20),
BARRIO VARCHAR2(20));

CREATE SEQUENCE SEQ_PRODUCTOS START WITH 1;

CREATE TABLE PRODUCTOS (ID_PRODUCTO NUMBER DEFAULT SEQ_PRODUCTOS.nextval PRIMARY KEY  NOT NULL, 
PRODUCTO VARCHAR2(20) NOT NULL, 
COSTO NUMBER(10) NOT NULL);

CREATE SEQUENCE SEQ_CLIENTES START WITH 1;

CREATE TABLE CLIENTES (ID_CLIENTES NUMBER DEFAULT SEQ_CLIENTES.nextval PRIMARY KEY  NOT NULL,
ID_USER NUMBER NOT NULL,
ID_PRODUCTO NUMBER NOT NULL,
FOREIGN KEY (ID_USER) REFERENCES USUARIO_DEUDA(ID_USER),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO));

CREATE SEQUENCE SEQ_EMPRESA START WITH 1;

CREATE TABLE EMPRESAS (ID_EMPRESA NUMBER DEFAULT SEQ_EMPRESA.nextval PRIMARY KEY  NOT NULL, 
NOMBRE VARCHAR2(20) NOT NULL,
CIUDAD VARCHAR(20) NOT NULL,
BARRIO VARCHAR(20) NOT NULL,
TIEMPO_VISITA NUMBER(4) NOT NULL,
TIEMPO_DESPLAZAMIENTO NUMBER(4) NOT NULL);

CREATE SEQUENCE SEQ_AGENTES START WITH 1;

CREATE TABLE AGENTES (ID_AGENTE NUMBER DEFAULT SEQ_AGENTES.nextval PRIMARY KEY  NOT NULL, 
NOMBRE VARCHAR2(20) NOT NULL,
CIUDAD VARCHAR(20) NOT NULL,
BARRIO VARCHAR(20) NOT NULL,
ID_EMPRESA NUMBER NOT NULL,
FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA));


CREATE SEQUENCE SEQ_ASIGNACION START WITH 1;

CREATE TABLE ASIGNACION (ID_ASIGNACION NUMBER DEFAULT SEQ_ASIGNACION.nextval PRIMARY KEY  NOT NULL, 
ID_USER NUMBER NOT NULL,
ID_AGENTE NUMBER NOT NULL,
FECHA DATE NOT NULL,
FOREIGN KEY (ID_USER) REFERENCES USUARIO_DEUDA(ID_USER),
FOREIGN KEY (ID_AGENTE) REFERENCES AGENTES(ID_AGENTE));

CREATE SEQUENCE SEQ_PRIORIDAD START WITH 1;

CREATE TABLE PRIORIDAD (ID_PRIORIDAD NUMBER DEFAULT SEQ_PRIORIDAD.nextval PRIMARY KEY  NOT NULL, 
CIUDAD VARCHAR(20) NOT NULL,
BARRIO VARCHAR(20) NOT NULL);

CREATE SEQUENCE SEQ_PARAMETRO START WITH 1;

CREATE TABLE PARAMETROS(ID_PARAMETRO NUMBER DEFAULT SEQ_PARAMETRO.nextval PRIMARY KEY  NOT NULL,
ID_EMPRESA NUMBER NOT NULL,
TIPO_CLIENTE VARCHAR2(20) NOT NULL,
CIUDAD VARCHAR2(20) NOT NULL,
DEUDA_MIN NUMBER(38,2) NOT NULL,
DEUDA_MAX NUMBER(38,2) NOT NULL,
ANTIGUEDAD_MIN NUMBER(4) NOT NULL,
ANTIGUEDAD_MAX NUMBER(4) NOT NULL,
PRODUCTOS_MIN NUMBER(4) NOT NULL,
PRODUCTOS_MAX NUMBER(4) NOT NULL,
FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS(ID_EMPRESA));